#!/usr/bin/env bash

cd 'users'
mkdir 'ben'
cd 'ben'
git clone https://github.com/whittlbc/mybot.git
cd 'mybot' 
heroku create
git push heroku master
heroku ps:scale web=1
echo "Successfully created new GH repo, sandbox Heroku server, and Node-Express app!"




